### ISSUE TITLE
CHAP5_eqs.ipynb에서 분모와 분자를 반대로 적으셔서 이렇게 글을 남깁니다.

### ISSUE THREAD

**Issue by young-hwanlee** [metamath1/noviceml#1]
[CHAP5_eqs.ipynb](https://github.com/metamath1/noviceml/blob/master/CHAP5_eqs.ipynb)의 [지수함수의 극한]에서 수식 1 아래에 "분자 x와 분모 exp(x) - 1"이라고 되어 있는데, "분모 x와 분자 exp(x) - 1"로 변경함이 옳지 않을까 해서 이렇게 글을 남깁니다.

**Comment by metamath1** [comment]
안녕하세요. 오류 수정하였습니다. 감사합니다.
