### ISSUE TITLE
CHAP3_eqs.ipynb과 CHAP5_eqs.ipynb에 대해서...

### ISSUE THREAD

**Issue by young-hwanlee** [metamath1/noviceml#2]
CHAP3_eqs.ipynb과 CHAP5_eqs.ipynb이 실제로는 각각 2장과 4장에 해당하는 내용입니다. 파일 이름을 바꾸심이 좋을 것 같아요.

**Comment by metamath1** [comment]
보조 자료까지 세심하게 읽어주셔서 감사합니다. 파일 이름 수정했습니다.
