### ISSUE TITLE
CHAP_10.ipynb 코드에서 코멘트 수정

### ISSUE THREAD

**Issue by young-hwanlee** [metamath1/noviceml#3]
CHAP_10.ipynb에서 "[그림 10-6] 넘파이 vs 사이킷런 선형회귀 결과"에 대한 코드 코멘트에 오타가 있습니다. sklearn을 이용하는 부분에 "M차 다항식"이라고 되어있는데, 책 331페이지에서처럼 "P차 다항식"으로 고쳐야 될 것 같습니다.

**Comment by metamath1** [comment]
안녕하세요. 오타 수정했습니다. 꼼꼼하게 봐주셔서 감사합니다.
